#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'hps_fpga' in
 * file './hps_fpga.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'vectorial_mem_0', class 'vectorial_mem'
 * The macros are prefixed with 'VECTORIAL_MEM_0_'.
 * The prefix is the slave descriptor.
 */
#define VECTORIAL_MEM_0_COMPONENT_TYPE vectorial_mem
#define VECTORIAL_MEM_0_COMPONENT_NAME vectorial_mem_0
#define VECTORIAL_MEM_0_BASE 0x0
#define VECTORIAL_MEM_0_SPAN 16
#define VECTORIAL_MEM_0_END 0xf


#endif /* _ALTERA_HPS_0_H_ */
